// src/components/Modal.svelte
<script lang="ts">
  import ArrowRightBold from "svelte-material-icons/ArrowRightBold.svelte";
  export let editsMade = false;
  export let links = false; // used in some modals
  export let close: () => void;
  export let save: () => void;
</script>

<main
  on:click={(e) => {
    //@ts-ignore
    const tagName = e.target?.tagName;
    if (tagName === "MAIN" && !editsMade) {
      close();
    }
  }}
  on:keypress={() => null}
  style="background: rgba(0,0,0,0.5)"
  class="fixed top-0 left-0 z-20 grid h-full min-h-screen w-full place-items-center"
>
  <div
    class="flex w-full max-w-[500px] flex-col gap-2 border border-gray-700 bg-gray-800 p-4 sm:rounded-md"
  >
    <slot><!-- optional fallback --></slot>
    <div class="flex gap-4">
      <button
        class="flex-1 rounded-md border border-gray-400 bg-gray-500 p-2 text-center"
        on:click={close}>Cancel</button
      >
      <button
        disabled={!editsMade}
        class="flex-1 rounded-md border border-blue-400 bg-blue-500 p-2 text-center"
        on:click={save}>Save</button
      >
    </div>
  </div>
  {#if links}
    <div class="fixed bottom-5 right-5 flex w-[200px] flex-col gap-4">
      <a
        href="/dashboard/projects"
        class="flex items-center justify-center gap-2 rounded-md border border-gray-500 bg-gray-800 p-4 text-xl text-gray-50 shadow-xl"
        >Dashboard <ArrowRightBold /></a
      >
    </div>
  {/if}
</main>

// src/components/Modal.tsx
import { createEffect, createSignal } from "solid-js";
import { ModalData, setModalData } from "../lib/client/signals";

function Modal() {
  return (
    <main
      onClick={(e) => {
        if (e.target.tagName === "MAIN") {
          setModalData({ ...ModalData(), visible: false } as unknown as null);
        }
      }}
      style={
        ModalData()?.visible ? `pointer-events: all` : `pointer-events: none`
      }
      class={`fixed top-0 left-0 z-40 h-screen w-screen ${
        ModalData()?.visible ? "bg-[rgba(0,0,0,0.5)]" : ""
      }`}
    >
      <div
        style="transform: all 0.3s ease-in-out;"
        class={`absolute ${
          ModalData()?.visible
            ? "-translate-y-1/2 opacity-100"
            : "-translate-y-1/3 opacity-0"
        } left-1/2 top-1/2 flex w-full max-w-[450px] -translate-x-1/2 flex-col gap-4 rounded-lg bg-gray-800 p-4`}
      >
        <h1 class="border border-x-0 border-t-0 border-gray-700 pb-4 text-xl text-gray-50">
          {ModalData()?.header}
        </h1>
        <span class="text-gray-400">{ModalData()?.body}</span>
        {ModalData()?.options?.map((option) => (
          <button
            onClick={() => {
              setModalData({
                ...ModalData(),
                visible: false,
              } as unknown as null);
              option.action();
            }}
            class="w-full rounded-lg bg-blue-600 p-4 py-2 text-lg text-blue-200"
          >
            {option.text}
          </button>
        ))}
      </div>
    </main>
  );
}

export default Modal;
